services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-dev-container
    volumes:
      - plex_media:/data
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080" # Main application port
      - "3000:3000" # Gin proxy port for hot reload
    environment:
      - CGO_ENABLED=1 # Enable CGO for SQLite3 support
      - GIN_MODE=debug # Set to 'release' in production
      - LOG_LEVEL=debug
    # For development with hot-reload:
    # command: gin --appPort 8080 --port 3000 --immediate --path ./cmd/api run main.go
    command: gin --appPort 8080 --port 3000 --immediate --path ./cmd/ffmpeg run ffmpeg.go
    # Production alternative (uncomment and comment out the line above):
    # command: go run ./cmd/api/main.go

volumes:
  plex_media:
