// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: movies.sql

package repository

import (
	"context"
)

const getMovie = `-- name: GetMovie :one
SELECT id, title, created_at, updated_at FROM movies WHERE id = ?
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.queryRow(ctx, q.getMovieStmt, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
