// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
)

type Movie struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	ReleaseYear sql.NullInt64   `json:"release_year"`
	Genre       sql.NullString  `json:"genre"`
	Director    sql.NullString  `json:"director"`
	Rating      sql.NullFloat64 `json:"rating"`
	CreatedAt   sql.NullTime    `json:"created_at"`
}
