// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: movies.sql

package repository

import (
	"context"
)

const findAllMovies = `-- name: FindAllMovies :many
SELECT id, title, release_year, genre, director, rating, created_at FROM movies
`

func (q *Queries) FindAllMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.query(ctx, q.findAllMoviesStmt, findAllMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.Genre,
			&i.Director,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
