FROM media-manager-server-base:latest

RUN apt-get update && apt-get install -y \
    # ffmpeg \
    sqlite3 \
    libsqlite3-dev \
    # protobuf-compiler \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
# RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
# RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0