// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type CreateUserInput struct {
	Username       string  `json:"username"`
	AgeRestriction int     `json:"ageRestriction"`
	PinHash        *string `json:"pinHash,omitempty"`
	Role           string  `json:"role"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateUserInput struct {
	ID             string  `json:"id"`
	Username       string  `json:"username"`
	AgeRestriction int     `json:"ageRestriction"`
	PinHash        *string `json:"pinHash,omitempty"`
	Role           string  `json:"role"`
}

type User struct {
	ID             string `json:"id"`
	Username       string `json:"username"`
	AgeRestriction int    `json:"ageRestriction"`
	Role           string `json:"role"`
}
