package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"mms/common/graphql/generated"
)

// GetMovie is the resolver for the getMovie field.
func (r *queryResolver) GetMovie(ctx context.Context, id string) (*generated.Movie, error) {
	return r.MediaService.GetMovie(id)
}

// GetMovies is the resolver for the getMovies field.
func (r *queryResolver) GetMovies(ctx context.Context) ([]*generated.Movie, error) {
	panic(fmt.Errorf("not implemented: GetMovies - getMovies"))
}

// GetTvShow is the resolver for the getTvShow field.
func (r *queryResolver) GetTvShow(ctx context.Context, id string) (*generated.TvShow, error) {
	panic(fmt.Errorf("not implemented: GetTvShow - getTvShow"))
}

// GetTvShows is the resolver for the getTvShows field.
func (r *queryResolver) GetTvShows(ctx context.Context) ([]*generated.TvShow, error) {
	panic(fmt.Errorf("not implemented: GetTvShows - getTvShows"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
