# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/app.exe"
  cmd = "go build -o tmp/app.exe ./cmd/main.go"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  poll = true

[run]
  bin = "tmp/app.exe"
  env = ["GIN_MODE=debug"]
  log = "debug"
