services:
  # gateway:
  #   build:
  #     context: ./gateway
  #     dockerfile: Dockerfile
  #   container_name: gateway
  #   ports:
  #     - "${GATEWAY_PORT}:${GATEWAY_PORT}"
  #   volumes:
  #     - ./gateway:/gateway
  #     - ./shared:/shared
  #   env_file:
  #     - .env.docker
  #   working_dir: /gateway
  #   command: air

  websocket-service:
    build:
      context: ./services/websocket-service
      dockerfile: Dockerfile
    container_name: websocket-service
    ports:
      - "15000:15000"
    volumes:
      - ./services/websocket-service:/websocket-service
      - ./shared:/shared
    env_file:
      - .env.docker
    working_dir: /websocket-service
    command: air

  # user-service:
  #   build:
  #     context: ./services/user-service
  #     dockerfile: Dockerfile
  #   container_name: user-service
  #   ports:
  #     - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
  #   volumes:
  #     - plex_media:/data
  #     - ./services/user-service:/user-service
  #     - ./shared:/shared
  #   environment:
  #     - CGO_ENABLED=1
  #   env_file:
  #     - .env.docker
  #   working_dir: /user-service
  #   command: air

  # streaming-service:
  #   build:
  #     context: ./services/streaming-service
  #     dockerfile: Dockerfile
  #   container_name: streaming-service
  #   volumes:
  #     - plex_media:/data
  #     - ./services/streaming-service:/streaming-service
  #     - ./shared:/shared
  #   working_dir: /streaming-service
  #   ports:
  #     - "${STREAMING_SERVICE_PORT}:${STREAMING_SERVICE_PORT}"
  #     - "${STREAMING_SERVICE_PROXY_PORT}:${STREAMING_SERVICE_PROXY_PORT}"
  #   environment:
  #     - CGO_ENABLED=${CGO_ENABLED}
  #     - GIN_MODE=${GIN_MODE}
  #   command: gin --appPort ${STREAMING_SERVICE_PORT} --port ${STREAMING_SERVICE_PROXY_PORT} --immediate --path ./cmd/videoStream run main.go

volumes:
  plex_media:
