name: Build and Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Create Installer
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
          cache: true
      
      - name: Install dependencies
        run: go mod download
      
      - name: Build application
        run: |
          go build -v -o dist/mediamanager.exe ./cmd/ffmpeg/
      
      - name: Download FFmpeg
        run: |
          mkdir -p dist/bin
          # Download FFmpeg Windows build (static)
          curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -o ffmpeg.zip
          7z x ffmpeg.zip -odist/
          move dist/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe dist/bin/
          move dist/ffmpeg-master-latest-win64-gpl/bin/ffprobe.exe dist/bin/
      
      - name: Create application folders
        run: |
          mkdir -p dist/database/data
          mkdir -p dist/database/migrations
          copy database/migrations/*.sql dist/database/migrations/
          copy database/sqlc.yaml dist/database/
      
      - name: Create Installer with InnoSetup
        run: |
          choco install innosetup -y
          # Create InnoSetup script
          echo '
          [Setup]
          AppName=Media Manager
          AppVersion=1.0.0
          DefaultDirName={pf}\MediaManager
          DefaultGroupName=Media Manager
          OutputDir=output
          OutputBaseFilename=MediaManagerSetup
          Compression=lzma
          SolidCompression=yes
          
          [Files]
          Source: "dist\mediamanager.exe"; DestDir: "{app}"
          Source: "dist\bin\*"; DestDir: "{app}\bin"; Flags: recursesubdirs
          Source: "dist\database\*"; DestDir: "{app}\database"; Flags: recursesubdirs
          Source: "video.html"; DestDir: "{app}"
          
          [Icons]
          Name: "{group}\Media Manager"; Filename: "{app}\mediamanager.exe"
          Name: "{commondesktop}\Media Manager"; Filename: "{app}\mediamanager.exe"
          
          [Registry]
          Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: expandsz; ValueName: "PATH"; ValueData: "{olddata};{app}\bin"; Check: NeedsAddPath(ExpandConstant(''{app}\bin''))
          
          [Code]
          function NeedsAddPath(Param: string): boolean;
          var
            OrigPath: string;
          begin
            if not RegQueryStringValue(HKLM, ''SYSTEM\CurrentControlSet\Control\Session Manager\Environment'', ''PATH'', OrigPath)
            then begin
              Result := True;
              exit;
            end;
            Result := Pos(';'' + Param + '';'', '';'' + OrigPath + '';'') = 0;
          end;
          ' > installer.iss
          
          # Build installer
          iscc installer.iss
      
      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: MediaManager-Installer
          path: output/MediaManagerSetup.exe
      
      # Release the installer when a tag is pushed
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/MediaManagerSetup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
